# Lines configured by zsh-newuser-install
fpath+=~/.zfunc

HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
unsetopt beep
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/zaechus/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# PATH
path+=("$HOME/.cargo/bin")
path+=("$HOME/.local/bin")

export PATH

# ENVVARS
export EDITOR="nvim"
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
export PAGER="bat"
export XDG_CURRENT_DESKTOP="sway"
export MOZ_ENABLE_WAYLAND=1

lt() {
    l --git-ignore -TL $1 $2 | bat -p
}
lta() {
    l -aT $1 | bat -p
}

# PROMPT
PROMPT=$'\n'"%F{6}%~%f"$'\n'"%B%(#.%F{1}.%F{2})%# %f%b"
