set number
set nowrap

set tabstop=8 softtabstop=0 expandtab shiftwidth=4 smarttab

set splitright
set splitbelow

colorscheme desert

" tree
map <F3> :set nosplitright<CR> :vsp .<CR> :vert res 22<CR> :set splitright<CR>
